name: push_notification
description: Local push notification app
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  device_info_plus: ^9.0.2
  http: ^1.1.0
  uuid: ^3.0.7
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
